### ISSUE TITLE
Add pgAdmin container for development purposes

### ISSUE THREAD

**Issue by thinkh** [Caleydo/tdp_publicdb#83]
We should prepare a pgAdmin container for development purposes in the docker-compose.partial.yml. The container should be commented out by default, so that developers can activate them on demand.

In the following a sample config that can be adapted.

```yml
  pgadmin:
    links:
      - db_publicdb:publicdb
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - db_publicdb
```
